name: Burns Compilers Testing

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    # permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Compile and Test
        run: mvn --batch-mode test
      - name: Communicate with GitHub Classroom
        if: always()
        uses: education/autograding@v1
